### ISSUE TITLE
Sass::SyntaxError: File to import not found or unreadable: bootstrap

### ISSUE THREAD

**Issue by alanalvespi** [200Creative/spree_bootstrap_frontend#105]
When deploying in production with capistrano I got the following error:
Sass::SyntaxError: File to import not found or unreadable: bootstrap

**Comment by A-James** [comment]
Hello,

Unfortunately you'll have to provide more information. Please include steps to reproduce, including environmental and setup information.

It sounds like an environmental problem rather than a spree_bootstrap_frontend problem.

Thanks

**Comment by patrickmcelwee** [comment]
In case anyone else comes across this ... this happened to me in development, but a server restart resolved it
